name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  page_flip_builder: ^0.1.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Helvetica Neue
      fonts:
        - asset: assets\fonts\HelveticaNeueMedium.otf
          weight: 700
